import { useEffect, useMemo, useState } from "react";
import { Activity, ArrowDownLeft, ArrowUpRight, Clock3, Code2, Copy, RefreshCw, Search } from "lucide-react";
import { api, type ApiLog } from "./api";

export function ApiLogsView({ onNotice }: { onNotice: (message: string) => void }) {
  const [logs, setLogs] = useState<ApiLog[]>([]);
  const [search, setSearch] = useState("");
  async function load() { try { setLogs((await api.logs()).data); } catch (error) { onNotice(error instanceof Error ? error.message : "Could not load API logs"); } }
  useEffect(() => { void load(); }, []);
  const filtered = useMemo(() => logs.filter((log) => `${log.method} ${log.path} ${log.status} ${log.trace_id}`.toLowerCase().includes(search.toLowerCase())), [logs, search]);
  const failures = logs.filter((log) => log.status >= 400).length;
  const average = logs.length ? Math.round(logs.reduce((sum, log) => sum + log.duration_ms, 0) / logs.length) : 0;
  return <section className="api-logs-page"><div className="page-title"><div><span className="eyebrow"><Code2 size={14}/> INTEGRATION OBSERVABILITY</span><h1>API logs</h1><p>Correlated inbound and outbound requests without sensitive request or response bodies.</p></div><button className="refresh-button" onClick={() => void load()}><RefreshCw size={15}/>Refresh</button></div><div className="activity-metrics"><article><span className="metric-icon blue"><Activity size={18}/></span><div><small>REQUESTS</small><strong>{logs.length}</strong></div></article><article><span className="metric-icon amber"><Clock3 size={18}/></span><div><small>AVERAGE LATENCY</small><strong>{average}ms</strong></div></article><article><span className="metric-icon violet"><Code2 size={18}/></span><div><small>ERRORS</small><strong>{failures}</strong></div></article></div><div className="activity-toolbar"><div><Search size={16}/><input placeholder="Search method, path, status, or trace ID" value={search} onChange={(event) => setSearch(event.target.value)}/></div></div><div className="api-table panel"><div className="api-head"><span>Direction</span><span>Request</span><span>Status</span><span>Latency</span><span>Actor</span><span>Trace</span><span>Time</span></div>{filtered.map((log) => <div className="api-row" key={log.id}><span className={log.direction}>{log.direction === "inbound" ? <ArrowDownLeft size={14}/> : <ArrowUpRight size={14}/>} {log.direction}</span><span><strong>{log.method}</strong>{log.path}</span><span className={log.status >= 400 ? "http-error" : "http-ok"}>{log.status}</span><span>{log.duration_ms}ms</span><span>{log.actor_id ?? "system"}</span><button title="Copy trace ID" onClick={() => { void navigator.clipboard.writeText(log.trace_id); onNotice("Trace ID copied."); }}><Copy size={13}/>{log.trace_id.slice(0, 10)}</button><span>{formatDate(log.created_at)}</span></div>)}</div></section>;
}
function formatDate(value: string) { const date = new Date(value.endsWith("Z") ? value : `${value.replace(" ", "T")}Z`); return Number.isNaN(date.valueOf()) ? value : new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric", hour: "numeric", minute: "2-digit", second: "2-digit" }).format(date); }
