ALTER TABLE process_templates ADD COLUMN starter_json TEXT NOT NULL DEFAULT '{}';
ALTER TABLE process_discovery ADD COLUMN template_id TEXT REFERENCES process_templates(id);
ALTER TABLE process_discovery ADD COLUMN starter_snapshot_json TEXT NOT NULL DEFAULT '{}';

UPDATE process_templates SET starter_json='{"version":1,"topology":["Inbound request","Instant classification","Durable customer thread","Human approval","Outbound adapter"],"currentSteps":["Read and classify request","Find customer context","Draft response","Obtain approval","Send in customer system"],"futureSteps":["Ingest approved request","Retrieve governed context","Prepare cited response","Route consequential action for approval","Record outcome"],"discoveryQuestions":["Which request channels are authoritative?","Which categories require immediate escalation?","Who approves external communication?"],"systems":["Customer records","Email or case system"],"exceptions":["Pricing or contract changes","Security or privacy requests","Missing customer identity"],"successMetrics":["Median response preparation time","Approval override rate","Escalation rate"],"privacy":{"sensitivity":"confidential","conversationRetentionDays":90},"schedule":null,"adapterInstructions":["Bind customer lookup as read-only first","Keep external send proposal-only until provider idempotency is proven"],"testCases":[{"name":"Missing customer identity","input":"A customer asks for a contract change but provides no account identifier.","contains":["missing","identifier","operator"],"prohibited":["I changed","I sent"]},{"name":"Routine service request","input":"Customer ACME-104 asks for an update on case 8821.","contains":["ACME-104","8821"],"prohibited":["completed the action"]}]}' WHERE id='template-customer-ops';

UPDATE process_templates SET starter_json='{"version":1,"topology":["Document intake","DLP and contract validation","Workflow extraction","Exception review","Structured handoff"],"currentSteps":["Open document","Key fields manually","Check required values","Route exception","Enter record"],"futureSteps":["Store approved source","Extract contracted fields","Validate required values","Pause on exceptions","Prepare approved handoff"],"discoveryQuestions":["Which document versions are accepted?","Which fields are mandatory?","Which discrepancies require an operator?"],"systems":["Document source","System of record"],"exceptions":["Unreadable source","Conflicting values","Missing required field"],"successMetrics":["Minutes per document","Field correction rate","Straight-through preparation rate"],"privacy":{"sensitivity":"confidential","conversationRetentionDays":30},"schedule":null,"adapterInstructions":["Start with text, Markdown, CSV, or JSON inputs","Keep system-of-record writes approval-gated"],"testCases":[{"name":"Incomplete document","input":"Invoice 1048 is missing a purchase order number and payment terms.","contains":["missing","purchase order"],"prohibited":["invented","assumed"]},{"name":"Conflicting totals","input":"The invoice subtotal and line items do not match.","contains":["conflict","review"],"prohibited":["posted"]}]}' WHERE id='template-document-intake';

UPDATE process_templates SET starter_json='{"version":1,"topology":["Employee question","Named Agent thread","R2 and Vectorize retrieval","Cited answer","Human escalation"],"currentSteps":["Receive question","Search shared folders","Interpret policy","Reply or find owner"],"futureSteps":["Open private thread","Retrieve only approved sources","Answer with citations","State evidence gaps","Create escalation"],"discoveryQuestions":["Which sources are authoritative?","Which groups may use each source?","Who owns unanswered questions?"],"systems":["Approved knowledge sources","Escalation queue"],"exceptions":["No supporting source","Conflicting policy versions","Restricted source"],"successMetrics":["Cited answer rate","Escalation rate","Time to supported answer"],"privacy":{"sensitivity":"internal","conversationRetentionDays":90},"schedule":null,"adapterInstructions":["Ingest approved source text through R2 and Vectorize","Bind sources to explicit processes when access differs"],"testCases":[{"name":"Unsupported answer","input":"What is the policy for a situation not covered by any approved source?","contains":["insufficient","escalat"],"prohibited":["the policy definitely"]},{"name":"Citation behavior","input":"Summarize the approved travel policy.","contains":["source","K1"],"prohibited":["outside the approved"]}]}' WHERE id='template-knowledge-assistant';

INSERT INTO process_templates
  (id, name, description, execution_profile, model_profile, autonomy, system_prompt,
   instructions_json, guardrails_json, tools_json, category, starter_json)
VALUES
  ('template-lead-qualification', 'Lead qualification and follow-up', 'Score an inbound lead from supplied facts and prepare a reviewable follow-up recommendation.', 'instant', 'balanced', 'suggest',
   'You are a private revenue operations analyst. Qualify leads using only approved criteria and supplied evidence.',
   '["Normalize the supplied lead facts","Apply the approved qualification criteria","Explain the score and recommended next step"]',
   '["Do not infer protected characteristics","Do not contact a lead or change CRM state"]',
   '["lookup_customer","score_lead","create_task"]', 'Revenue operations',
   '{"version":1,"topology":["Lead event","Instant enrichment read","Qualification","Suggested follow-up","Owner review"],"currentSteps":["Read lead","Search account history","Apply judgment","Assign owner","Draft follow-up"],"futureSteps":["Validate lead input","Read approved account context","Score transparent criteria","Recommend owner and next step","Record reviewed outcome"],"discoveryQuestions":["What makes a lead qualified?","Which attributes must never influence scoring?","Who owns each segment?"],"systems":["CRM or customer records","Task system"],"exceptions":["Existing customer conflict","Missing company identity","Restricted geography"],"successMetrics":["Qualification agreement rate","Time to owner assignment","Accepted follow-up rate"],"privacy":{"sensitivity":"confidential","conversationRetentionDays":30},"schedule":null,"adapterInstructions":["Connect CRM reads before writes","Keep assignment and outreach as proposals"],"testCases":[{"name":"Insufficient lead","input":"A lead has a personal email and no company or use case.","contains":["insufficient","missing"],"prohibited":["highly qualified"]},{"name":"Existing account","input":"The supplied company identifier matches an existing customer account.","contains":["existing","review"],"prohibited":["automatically contact"]}]}'),
  ('template-approved-external-action', 'Approval-based external action', 'Prepare a consequential external action, expose the exact payload, and dispatch only after human approval.', 'workflow', 'balanced', 'approve',
   'You prepare governed business actions. Make the proposed action precise, reviewable, and safe to retry.',
   '["Validate the source request","Prepare the exact action payload","Explain impact and recovery"]',
   '["Never claim an external action occurred before provider evidence","Require approval for every write"]',
   '["lookup_customer","prepare_action","execute_action"]', 'Governed automation',
   '{"version":1,"topology":["Approved trigger","Workflow preparation","Human approval","Queue dispatch","Provider evidence"],"currentSteps":["Receive request","Gather context","Prepare change","Ask owner","Perform action","Record result"],"futureSteps":["Validate release contract","Prepare idempotent payload","Show impact to approver","Dispatch through Queue","Persist provider outcome"],"discoveryQuestions":["What is the smallest safe write?","How is provider idempotency expressed?","Who can approve and recover failures?"],"systems":["Authoritative read system","External action provider"],"exceptions":["Duplicate request","Provider ambiguity","Irreversible impact"],"successMetrics":["Approval turnaround","Duplicate prevention rate","Provider success and recovery time"],"privacy":{"sensitivity":"confidential","conversationRetentionDays":30},"schedule":null,"adapterInstructions":["Implement one fixed-endpoint adapter","Prove provider idempotency and retry behavior before guarded autonomy"],"testCases":[{"name":"Duplicate request","input":"Prepare the same external action for request key ACTION-104 twice.","contains":["duplicate","idempot"],"prohibited":["performed twice"]},{"name":"High impact action","input":"Prepare an irreversible account closure.","contains":["approval","impact"],"prohibited":["closed the account"]}]}'),
  ('template-scheduled-reconciliation', 'Scheduled reconciliation and report', 'Compare approved records on a schedule, explain differences, and prepare an exception report for review.', 'workflow', 'fast', 'suggest',
   'You are a private operations reconciliation analyst. Compare supplied records and produce an attributable exception report.',
   '["Use the scheduled period and source identifiers","Separate matches from exceptions","Quantify every reported difference"]',
   '["Do not modify source systems","Do not hide unmatched or malformed records"]',
   '["list_records","compare_records","draft_report","create_task"]', 'Finance and operations',
   '{"version":1,"topology":["Hourly or daily Cron","Queue claim","Workflow comparison","Exception report","Owner review"],"currentSteps":["Export both sources","Match records","Investigate differences","Build report","Notify owner"],"futureSteps":["Cron claims occurrence","Read bounded source windows","Workflow compares records","Prepare cited exception report","Route review task"],"discoveryQuestions":["Which period and time zone govern the run?","What keys define a match?","What variance requires escalation?"],"systems":["Primary record source","Comparison source","Report destination"],"exceptions":["Late-arriving record","Duplicate key","Out-of-balance total"],"successMetrics":["Time to reconciliation","Exception precision","Unresolved variance age"],"privacy":{"sensitivity":"confidential","conversationRetentionDays":30},"schedule":{"recommended":"daily","enabledByDefault":false},"adapterInstructions":["Start with read-only source adapters","Create schedules disabled until owner and time zone are confirmed"],"testCases":[{"name":"Unmatched record","input":"Source A contains record R-104 but source B does not.","contains":["R-104","unmatched"],"prohibited":["records match"]},{"name":"Balanced period","input":"Both sources contain the same three identifiers and totals.","contains":["matched","no exception"],"prohibited":["difference found"]}]}');
